### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by user1342** [KonradIT/parler-py-api#1]
I'm getting an `Exception: {'status': 401}` error when running, for example, `python3 01_stop_the_steal.py`. I'm fairly sure this is simply down to me not having set the environment variable tokens (`JST `and `MST`). However, my main question is where Parler provides these tokens, as searching for their API there doesn't appear to be much documentation (possibly worth an addition to the README)?

Cheers.

**Comment by KonradIT** [comment]
Hi, you have to get the MST and JST tokens from the cookies in your browser.

**Comment by user1342** [comment]
Ah, great that's done it - cheers.! Great tool by the way 👍

**Comment by olli93jo** [comment]
Getting the same error `Exception: {'status': 401, 'error': 'Unauthorized', 'message': 'Most likely unauthorized or no results'}`. However, I inserted my `MST` and `JST` tokens from my browser. Do u have any idea what I could do to mitigate this?

**Comment by KonradIT** [comment]
Hi, yes, you have to decrease how often you execute a call.

**Comment by olli93jo** [comment]
I decreased the variables `max_sleep_limit` and also the number in the data variable, if it's that what you mean with 'decrease how often you execute a call'. Still, getting the same error.

**Comment by KonradIT** [comment]
Sorry, increase.

**Comment by olli93jo** [comment]
Sorry if its getting annoying. I increased the values of these variables, but still its not working. Now it's only running longer till I get the error message. 

I'm not sure if its because of the data folder? I simply created a 'data' folder in my project folder. However, this should have nothing to do with Error 401, right?
