### ISSUE TITLE
Is there a ability to fetch followers names from the specific profile?

### ISSUE THREAD

**Issue by TomaszKot11** [KonradIT/parler-py-api#10]
Hi @KonradIT @ExtraLime . Just came across this project. Is there a possibility to fetch the followers names from the specific profile?

**Comment by KonradIT** [comment]
Hi, not yet.

**Comment by TomaszKot11** [comment]
Thanks @KonradIT  . Does the API used in the `Parler` class have any documentation or does it have such a possibility? 😄 Out of curiosity do you plan to add it in the future? It would be extremely useful.

**Comment by KonradIT** [comment]
There is no documentation on the official parler.com API, hence this project. I've added the function `followers` to `Parler` which you can use.

**Comment by KonradIT** [comment]
Uploaded, let me know if it works, it requires a `creator id` which you can get using the `profile` function.

**Comment by TomaszKot11** [comment]
Hey @KonradIT  thank you a lot!!! But... After doing some testing it is not working for me 🤔 I provide sample screenshot and the code: 

```
from Parler import Parler 

parler = Parler(jst="MY JST GOES HERE", mst="MY JST GOS HERE", debug=False)


print(parler.profile(username='TuckerCarlson'))


creator = parler.profile(username='TuckerCarlson')
print(parler.followers(creator.get('id')))
```
Maybe I misunderstood something? 🤔 

![image](https://user-images.githubusercontent.com/35807407/102145504-a6726300-3e67-11eb-807a-fe6a37117d5d.png)

**Comment by KonradIT** [comment]
Right, fixed, should be working now.

**Comment by TomaszKot11** [comment]
Confirmed, it works! Thank you for your support!

**Comment by TomaszKot11** [comment]
Issue solved, closing
