### ISSUE TITLE
How do I get the the MST and JST tokens?

### ISSUE THREAD

**Issue by elisabettabiondi** [KonradIT/parler-py-api#17]
Hi,
I am new to using Parler. I have understood that I should get MST and JST tokens from the cookies on Chrome, but I simply see only one long string (see screenshot)
![screenshot](https://user-images.githubusercontent.com/53190518/119322912-6c12ba80-bc7e-11eb-9dba-f7c858b54a9a.PNG)
I do not understand if this is because the Parler settings/API has changed, but your code needs these values. In which way can I get them?

**Comment by KonradIT** [comment]
Closing due to incompatibility with v2 branch.
