### ISSUE TITLE
API is disabled. Please upgrade to latest version.

### ISSUE THREAD

**Issue by giltal1** [KonradIT/parler-py-api#19]
During the last weeks I get this error message from the API endpoint.
`API is disabled. Please upgrade to latest version.`
Is there a fix?

**Comment by KonradIT** [comment]
Hi, no idea, I'm still trying to figure out what to do with this project, I'm working on a bs4 based alternative to get posts.

**Comment by KonradIT** [comment]
Library is back up and running, check out v2 branch.
